
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
 
import "@/style/App.scss";
import "@/style/index.scss";
import { ConfigProvider } from "antd";
import 'primeflex/primeflex.css';
import Footer from "../(components)/footer/Footer";
import Navbar from "../(components)/navbar/Navbar";

export const metadata = {
  title: "Right Click",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = params;
  const messages = await getMessages();
  const theme = {
    token: {
      fontSize: 16,
      colorPrimary: '#FA6409',
    },
  };
  return (
    <html lang={locale} dir={locale == "en" ? 'ltr' : 'rtl'} >
      <head>
        <link rel="icon" type="image/png" href="/favicon.ico" />
      </head>
      <body>
        <ConfigProvider  theme={theme}>
          <NextIntlClientProvider messages={messages}>
            <Navbar />
            {children}
            <Footer />
          </NextIntlClientProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
