
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Cairo } from "next/font/google";

import { ConfigProvider } from "antd";
import 'primeflex/primeflex.css';
import { Suspense } from "react";
import Footer from "../(components)/footer/Footer";
import Navbar from "../(components)/navbar/Navbar";
import Loading from "./loading";



import "@/style/App.scss";
import "@/style/index.scss";

const mainFont = Cairo({
  subsets: ['arabic','latin'],
  weight: ["400"],

})
 
export const metadata = {
  title: "Right Click",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = params;
  const messages = await getMessages();
  const theme = {
    token: {
      colorPrimary: '#0A1220',
      colorActiveText: 'red'
    },
    components: {

    },
  };
  return (
    <html lang={locale} dir={locale == "en" ? 'ltr' : 'rtl'} >
      <head>
        <link rel="icon" type="image/png" href="/favicon.ico" />
      </head>
      <body style={{ fontFamily: mainFont.style.fontFamily }}>
        <ConfigProvider theme={theme}>
          <NextIntlClientProvider messages={messages}>
            <Suspense fallback={<Loading />} >
              <Navbar />
              {children}
              <Footer />
            </Suspense>
          </NextIntlClientProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
