
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Cairo, Poppins } from "next/font/google";

import { ConfigProvider } from "antd";
import 'primeflex/primeflex.css';
import { Suspense } from "react";
import Footer from "../(components)/footer/Footer";
import Navbar from "../(components)/navbar/Navbar";
import Loading from "./loading";



import "@/style/App.css";
import "@/style/index.css";

const fontAr = Cairo({
  subsets: ['arabic','latin','latin-ext'],
  weight: ["400","200","300"],

})

const fontEn = Poppins({
  subsets: ["latin","latin-ext"],
  weight: ["400", "100", "200", "300","400","500","600","700","800"],
})



export const metadata = {
  title: "Right Click",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {

  const { locale } = params;
  const messages = await getMessages();
  console.log(locale);

  const theme = {
    token: {
      colorPrimary: "#0A1220",
      colorActiveText: "red",
      fontFamily: locale === "en" ? fontEn.style.fontFamily : fontAr.style.fontFamily,
    },
    components: { 
      Typography: {
        fontFamily: locale === "en" ? fontEn.style.fontFamily : fontAr.style.fontFamily,
      },
      Dropdown:{
        fontFamily: locale === "en" ? fontEn.style.fontFamily : fontAr.style.fontFamily,
      },
      Button: {
        fontFamily: locale === "en" ? fontEn.style.fontFamily : fontAr.style.fontFamily,
      },
      Spin: {
        customColor: "#FA6409", // Custom property for spin color
      },
    },
  };
  
  return (
    <html lang={locale} dir={locale == "en" ? 'ltr' : 'rtl'} >
      <head>
        <link rel="icon" type="image/png" href="/favicon.ico" />
      </head>
      <body className="overflow-hidden" style={{ fontFamily: locale == "en" ? fontEn.style.fontFamily : fontAr.style.fontFamily }}>
        <ConfigProvider theme={theme}>
          <NextIntlClientProvider messages={messages}>
            <Suspense fallback={<Loading />} >
              <Navbar />
              {children}
              <Footer />
            </Suspense>
          </NextIntlClientProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
